import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import getServerSidePropsLoginMiddleware from '../middlware/getServerSidePropsLoginMiddleware';
import redirectToPage from '../utils/redirectToPage';
import { greetByTime } from '../utils/dates';
import BlankSearchSVGComponent from '@/components/shared/svg/Search/BlankSearchSVGComponent';

export default function Home({ user }) {
  return (
    <>
      <Head>
        <title>Movie Links</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          className={styles.tvImage}
          width={150}
          height={150}
          src="/images/tv.png"
          alt="Illustration of TV and popcorn"
        />
        <h1 className={styles.greeting}>{greetByTime(user.firstName)}</h1>
        <Link className={styles.searchShortcut} href="/search">
          <BlankSearchSVGComponent />
          <p>
            Looking for a movie or TV show?
            <br />
            <span>
              Try the search here
            </span>
          </p>
        </Link>
      </main>
    </>
  );
}

export const getServerSideProps = getServerSidePropsLoginMiddleware(async (context) => {
  try {
    const { user } = context.req.session;
    return { props: { user } };
  } catch (e) {
    return redirectToPage('/404');
  }
});
