import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import getServerSidePropsLoginMiddleware from '../middlware/getServerSidePropsLoginMiddleware';
import redirectToPage from '../utils/redirectToPage';
import { greetByTime } from '../utils/dates';

export default function Home({ user }) {
  return (
    <>
      <Head>
        <title>Movie Links</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{greetByTime(user.firstName)}</h1>
      </main>
    </>
  );
}

export const getServerSideProps = getServerSidePropsLoginMiddleware(async (context) => {
  try {
    const { user } = context.req.session;
    return { props: { user } };
  } catch (e) {
    return redirectToPage('/404');
  }
});
